### ISSUE TITLE
Problème des couleurs fonçées

### ISSUE THREAD

**Issue by joefrigo** [UQO-2019-INF1583/annotator#113]
**Description :**
À partir de l'interface de gestion de projet, l'attribution d'un background color foncées aux valeurs d'un type (Entity, Attributes, Events, Relations) cause un problème de lisibilité à un point tel qu'il est impossible de lire le texte qui y est inscrit. 

**Pour reproduire :**

- Créer un nouveau projet

- Naviguer à l'interface d'administration de projet

- Changer la couleur d'arrière-plan pour une valeur d'un certain type

**Résultat attendu**
![image](https://user-images.githubusercontent.com/25123205/65358998-21978b80-dbc9-11e9-9adb-a61b96ba8110.png)

**Résultat obtenu**
![image](https://user-images.githubusercontent.com/25123205/65359024-3411c500-dbc9-11e9-8af2-2b367d09a70e.png)

### Référence au cahier des charges
Section 5

**Comment by AliJM0369** [comment]
Probleme regle!

**Comment by AliJM0369** [comment]
Ce bug a deja ete regla et la solution se trouve dans: "Bug fixes #107 #113 #140"
