### ISSUE TITLE
Trois éléments d'un projet peuvent être créés avec un nom composé seulement des espaces 

### ISSUE THREAD

**Issue by Kwasi15** [UQO-2019-INF1583/annotator#117]
### Description :
Certains éléments du projet peuvent être créés avec un nom compose seulement d'espaces. Les éléments concernés par ce problème sont les suivants : Event (évènement), Entity (entité) et Attribut (attribut).

**Correcteur du bug** : Cristian Zubieta

Le problème a été solutionné sur la branche **bug#117_cristianzubieta**

### Pour reproduire : 

1. Se connecter avec un compte d'administrateur.
2. Naviguer à l'interface d'administration d'un projet pouvant être modifié. (S'il n'y a aucun projet pouvant être modifié, créer un nouveau projet avant de faire cette étape).
3. Créer un nouveau évènement (Event), un nouvel attribut (Attribut) ou une nouvelle entité (Entity) ayant un nom avec la valeur "    ".

![Modif impossible](https://user-images.githubusercontent.com/9216118/65367376-8f11df00-dbfe-11e9-86f6-410ff40b145f.JPG)

### Résultat attendu : 

- Le bouton "Add" devrait rester desactivé ("disabled") lorsque l'on tape un nom composé d'espaces seulement.
- Un message d'erreur devrait apparaître en dessous du champ "Name" , indiquant que le nom est obligatoire.

**N.B :** Dans le cas où le bouton "Add" _resterait toujours activé_ ("enabled") et que l'on essaie d'ajouter un élément avec un nom composé d'espaces seulement, l'application devrait refuser ce nom et afficher un message d'erreur à l'utilisateur.

### Résultat obtenu : 

- Le bouton "Add" s'active lorsque l'on tape un nom composé d'espaces seulement.
- Un message d'erreur n'apparaît pas en dessous du champ "Name" , indiquant que le nom est obligatoire.

**N.B :** Dans le cas où le bouton "Add" _resterait toujours activé_ ("enabled") et que l'on essaie d'ajouter un élément avec un nom composé d'espaces seulement, l'application ne refuse pas ce nom et sauvegarde l'élément.

### Niveau de défectuosité :
Modéré

### Référence au cahier des charges :

- 5.3.7 (pour une entité) 
- 5.4.6 (pour un attribut)
- 5.6.6.2 (pour un événement)

**Comment by levasseurv** [comment]
Est-ce que c'est seulement possible pour l'évènement ?

**Comment by Kwasi15** [comment]
Nom, c'est également possible sur Entities, Attributs, Relations

**Comment by TravellersID** [comment]
Modification de la documentation du Bug
