### ISSUE TITLE
Un compte supprimé peut toujours ouvrir une session

### ISSUE THREAD

**Issue by Kwasi15** [UQO-2019-INF1583/annotator#123]
**Reproduction du problème** 
Un compte a été créé avec mon courriel de l'UQO. Par la suite ce compte a été supprimé. Ce compte a tout de même pu ouvrir une session et mieux consulter les documents.
![ouvertureSessionInit](https://user-images.githubusercontent.com/9216118/65380927-defead80-dcb3-11e9-8a7f-4243a052c342.JPG)
![ouvertureSession](https://user-images.githubusercontent.com/9216118/65380930-ea51d900-dcb3-11e9-9153-b01f63b9e43a.JPG)
![consultation](https://user-images.githubusercontent.com/9216118/65380933-efaf2380-dcb3-11e9-984e-b067c498aa30.JPG)

**Solution** 
Revoir le code pour que la suppression du compte se fasse effectivement

**Comment by levasseurv** [comment]
L'utilisateur «supprimé» se trouve toujours dans les utilisateurs qui ont accès à la base de données (partie authentication de firebase) même si le document de la collection «Users» est supprimé

**Comment by levasseurv** [comment]
https://github.com/UQO-2019-INF1583/annotator/issues/129
