### ISSUE TITLE
Distinction entre Administrateur de Projets et Administrateur Système difficile à cerner

### ISSUE THREAD

**Issue by Kwasi15** [UQO-2019-INF1583/annotator#124]
**Problème** 
On a du mal à savoir si on est administrateur de projet ou administrateur système car entant qu'Administrateur de projet, on ne devrait pas pouvoir gérer les autres administrateurs de projets. Or avec notre compte, on peut le faire. 
En tant qu'Administrateur de projets, on peut supposer pouvoir gérer les projets d'un autre administrateur de projets. Actuellement celà n'est pas possible. Ce qui entraine une confusion ;a savoir si on est administrateur de projets ou administrateur système.
Le cahier de charge est muet sur cet aspect du projet.

**Solution** 
Revoir le cahier de charge pour redéfinir les rôles de manière plus précises

**Comment by levasseurv** [comment]
https://github.com/UQO-2019-INF1583/annotator/issues/127
