### ISSUE TITLE
Absence des "deux menus déroulants permettant le choix des catégories associées"

### ISSUE THREAD

**Issue by Kwasi15** [UQO-2019-INF1583/annotator#126]
### Description :
Le cahier de charges stipule au point 5.6.2. ceci : "Un bouton en haut de la liste permettra d'ajouter un nouvel événement. Lorsque le bouton est cliqué, un dialogue apparaîtra permettant le choix du nom et de la couleur de l’événement, ainsi que _**deux menus déroulants permettant le choix des catégories associées.**_"
On peut comprendre que les 2 catégories correspondent au Label et à l'attribut mais il n'y a pas de menus déroulants permettant le choix des catégories associées même si on prend soin de créer d'avance les attributs.

### Pour reproduire : 

- Créer un nouveau projet

- Naviguer à l'interface d'administration de projet du nouveau projet

- Appuyer sur le bouton + de la section **Events**

### Résultat attendu : 

Il devrait y avoir une liste déroulante pour les champs Labels et Attributes 

### Résultat obtenu : 

Il n'y a pas de liste déroulante pour ces champs; on doit écrire leur **Labels et Attributes**  à la main

![Event](https://user-images.githubusercontent.com/9216118/65381071-f0958480-dcb6-11e9-866d-6b9659070b2d.JPG)

### Niveau de défectuosité :
Modéré

### Référence au cahier des charges :
5.6.2

**Comment by TravellersID** [comment]
Modification de la documentation du Bug

**Comment by Nicolas-Rheaume** [comment]
La nouvelle interface de Projet permet d'ajouter plusieurs étiquettes et attributs à un évènement.
