### ISSUE TITLE
Bouton Ajouter peut être appuyé sans que les champs obligatoires ne soient remplis

### ISSUE THREAD

**Issue by MarieHTB** [UQO-2019-INF1583/annotator#132]
### Correctrice: Marie-Hélène Tanguay-Bérubé
Ce bogue a été solutionné sur la branche MarieHTB_bug#132

### Description : 

À l'ouverture de la fenêtre Corpus, on ne peut pas appuyer sur le bouton Ajouter mais lorsque le fichier .txt est sélectionné, il est possible d'appuyer sur ajouter sans qu'un titre ne soit choisi même si ce dernier est obligatoire. 

### Reproduction du bogue : 

Choisir le fichier .txt, le bouton Ajouter est activé comme ci-dessous

![AjouterCorpus1](https://user-images.githubusercontent.com/25113770/65390010-41de5c00-dd29-11e9-9b93-b9b9b81d0d64.png)

### Résultat attendu : 

Le bouton Ajouter devrait être inactif tant et aussi longtemps que les champs ne sont pas tous remplis. 

### Résultat obtenu : 

Lorsque le bouton Ajouter est sélectionné, nous sommes redirigés à la page de projet et le texte n'a pas été enregistré dans le corpus.

### Niveau de défectuosité : 
Majeur

### Référence au cahier des charges :
Section 5.2.1

**Comment by levasseurv** [comment]
Le texte est enregistré sans titre
![image](https://user-images.githubusercontent.com/7990942/66255684-9edc0800-e754-11e9-8adb-0ffcf938daca.png)

**Comment by MarieHTB** [comment]
J'ai réessayé et rien ne sauvegarde dans mon cas. 

![CorpusVide](https://user-images.githubusercontent.com/25113770/66258758-1327a300-e777-11e9-87b3-cd37776456e5.PNG)

**Comment by TravellersID** [comment]
Modification de la documentation du Bug
