### ISSUE TITLE
Incohérences entre les données requises par BRAT et ceux fournis par l’application

### ISSUE THREAD

**Issue by HugoBLapointe** [UQO-2019-INF1583/annotator#139]
**Description:** Il y a des incohérences entre les données requises par BRAT et ceux fournis par l’application.

**Résultat attendu:** Le données requises par BRAT devraient êtres les mêmes demandé par l’application à l’utilisateur

**Capture d’écran:** 

Capture 01: Données demandées par l’application
 
![image](https://user-images.githubusercontent.com/33591335/65436232-d612f680-ddef-11e9-8e70-bcdd793e8ff8.png)

Capture 02: Données requises par BRAT selon le cahier des charges
 
![image](https://user-images.githubusercontent.com/33591335/65436244-d9a67d80-ddef-11e9-8845-0b28e0eb7698.png)

**Comment by Nicolas-Rheaume** [comment]
La nouvelle interface de projet permet d'ajouter les bonnes données Brat selon leur type respectif.
