### ISSUE TITLE
Aucun message lorsqu'on tente d'annoter un texte dans un projet qui ne contient aucun type d'annotation

### ISSUE THREAD

**Issue by levasseurv** [UQO-2019-INF1583/annotator#140]
### Description :
Lorsqu'on tente d'annoter un texte dans un projet qui ne contient aucun type d'annotation, la boîte de dialogue d'annotation n'apparaît pas et aucune information à ce sujet n'est retournée à l'utilisateur.
### Pour reproduire :
1. Se connecter
2. Choisir un projet dans lequel : 
  - on a les droits d'annotation
  - qui contient au moins un texte dans le corpus
  - qui n'a aucune entité définie 
  ![image](https://user-images.githubusercontent.com/7990942/66173283-671e7480-e61d-11e9-8432-a655de4ed495.png)
3. Passer à l'annotation d'un des textes (bouton _view_)
4. Sélectionner une partie du texte

### Résultat obtenu :
Rien ne se produit. Aucun message n'est envoyé à l'utilisateur pour l'informer de la non disponibilité de la fonction d'annotation.

### Résultat attendu :
On ne devrait pas permettre l'annotation d'un document si aucun type d'annotation est disponible. L'utilisateur devrait être informé de cette limitation.

De l'information à cet effet doit aussi être ajoutée dans le cahier de charges.

**Comment by AliJM0369** [comment]
Ce bug a deja ete regla et la solution se trouve dans: "Bug fixes #107 #113 #140"
