### ISSUE TITLE
N'importe quel utilisateur peut supprimer un projet dans lequel il n'est pas un administrateur

### ISSUE THREAD

**Issue by chadi324** [UQO-2019-INF1583/annotator#141]

**Comment by chadi324** [comment]
Description :  Un administrateur du projet a accès aux boutons « Delete » pour effacer ses projets et même les projets des autres administrateurs .

Après que l'utilisateur s'enregistre, il est déjà connecté  .

Résultat attendu :
L’administrateur du projet doit être capable d’effacer ses propres projets uniquement et ne lui jamais donner l’accès a effacer autres projets dont ils l’appartiennent pas . 
Le bouton « Delete » doit être visible aux listes des projets dans lesquelles il est un un admistrateur .

Résultat obtenu :
Un admistrateur X du projet peut supprimer les projets d’un autre administrateur Y.

**Comment by levasseurv** [comment]
Dans quelle version du code ?

Je suis administrateur et je n'ai pas de boutons pour supprimer des projets qui ne sont pas les miens.

![image](https://user-images.githubusercontent.com/7990942/67977808-2d766480-fbef-11e9-9c71-fa9697b52ddd.png)

**Comment by iglewski** [comment]
Quelle section du cahier des charges mentionne que "L’administrateur du projet doit être capable d’effacer ses propres projets uniquement" ?
