### ISSUE TITLE
Possibilité pour un administrateur de supprimer le créateur d'un projet des administrateurs de celui-ci

### ISSUE THREAD

**Issue by TravellersID** [UQO-2019-INF1583/annotator#148]
### Description : 
La page de gestion d’utilisateurs est seulement accessible en entrant l’URL « http://localhost:4200/userManager » et elle est accessible par tous les utilisateurs authentifiés. Ces derniers ont toutes les permissions de modifier et supprimer d’autres utilisateurs même s’ils ne peuvent supprimer le projet (le bouton « Delete » n’est pas rouge). 

### Pour reproduire : 
1.	Créer deux comptes d’utilisateur valides et leur octroyer le rôle d’administrateur.
2.	Sur le premier profil, créer un nouveau projet en allant sur http://localhost:4200/createProject.
3.	Sur la page du nouveau projet, inviter le deuxième profil au projet comme administrateur et/ou annotateur.
4.	Se déconnecter du premier profil et se connecter au deuxième.
5.	Aller à la page du gestionnaire d’utilisateur (http://localhost:4200/userManager) et supprimer le premier compte des administrateurs du projet, soit le créateur du projet et celui qui nous y a invité.
6.	Regarder les administrateurs du projet. 

### Résultat attendu : 
Il devrait être impossible pour le deuxième utilisateur de supprimer un autre administrateur, à moins d’obtenir l’approbation d’un administrateur servant de juge (créateur du projet). L’administrateur d’origine ne devrait donc pas pouvoir être supprimé. 

### Résultat obtenu : 
L’administrateur d’origine a perdu les droits d’administration de son propre projet. 

### Niveau de défectuosité :
Majeur

### Référence au cahier des charges :
Section 5.7

**Comment by iglewski** [comment]
Je ne trouve rien dans la section 5.7 par rapport à ce bug.

**Comment by RaptorGTX** [comment]
Moi non plus, à la place j'ai modifié la section 2.1.3 à propos de l'administrateur du système.

**Comment by RaptorGTX** [comment]
Ce bug est réparé dans la branche https://github.com/UQO-2019-INF1583/annotator/tree/bug%23148CreateurDeProjetSupprime

William Grenon (GREW12089500)
