### ISSUE TITLE
Possible de modifier la description du projet sans être administrateur du projet

### ISSUE THREAD

**Issue by levasseurv** [UQO-2019-INF1583/annotator#97]
### Description : 
Lorsque l'on clique «view» sur un projet que l'on peut voir mais pas modifier, on peut tout de même changer le nom et la description du projet, mais pas les membres, le corpus ou les entités.

### Pour reproduire : 
1. Se connecter
2. Choisir un projet que l'on peut voir mais pas modifier; cliquer sur «View» («delete» ne sera pas disponible)
  ![image](https://user-images.githubusercontent.com/7990942/63815062-29814a00-c901-11e9-8ad7-06c6ddf4b2b1.png)
3. Modifier le nom ou la description du projet
4. Enregistrer (bouton «save»)
5. Retourner à la liste des projets et observer que les modifications ont bien été enregistrées

### Résultat attendu : 
Le titre du projet et sa description ne sont pas modifiables pour les utilisateurs qui ne sont pas administrateurs du projet. 

### Résultat obtenu : 
Les modifications sont enregistrées.

**Comment by ruthfokoua** [comment]
pour résoudre le problème j'ai ajouté le bouton Edit  qui est visible seulement lorsqu'on est administrateur du projet.
Le bouton Edit nous permet d'activer la modification de la description et le titre du projet. 
Dans ce cas ci je ne suis pas administrateur
![image](https://user-images.githubusercontent.com/16780080/69482862-856b4a00-0dee-11ea-8304-544cf9f6ea94.png)
![image](https://user-images.githubusercontent.com/16780080/69482873-a5027280-0dee-11ea-947e-29b3c7c7fa87.png)
cas ou je suis administrateur
![image](https://user-images.githubusercontent.com/16780080/69482888-dc711f00-0dee-11ea-9c9b-c8938fd206b0.png)
![image](https://user-images.githubusercontent.com/16780080/69482890-ec88fe80-0dee-11ea-924b-6532d8d03bda.png)
une fois que l'administrateur clique sur Edit  il verra deux boutons ( Save et cancel) apparaitre et le champs de modification va  devenir gris claire. Et une fois les modifications terminer il pourra faire des sauvegardes.
![image](https://user-images.githubusercontent.com/16780080/69482947-a2ece380-0def-11ea-87be-6019ccc18e66.png)
![image](https://user-images.githubusercontent.com/16780080/69482961-c6179300-0def-11ea-90be-c7de4f6d6b84.png)

**Comment by ruthfokoua** [comment]
https://github.com/UQO-2019-INF1583/annotator/tree/bug%2397 lien pour mon commit
